/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/ui/BaseButton.vue')['default']
    DragDialog: typeof import('./components/ui/DragDialog.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    MaskDialog: typeof import('./components/ui/MaskDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/ui/SvgIcon.vue')['default']
  }
}
